name:                assistant

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - universum

default-extensions:
  - NoImplicitPrelude

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings

tests:
  assistant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assistant
